---
# Global Variables for 'glance' Inventory Group

glance_filesystem_store_datadir: /var/opt/pf9/imagelibrary/data
glance_public_endpoint: False
glance_images:
  - https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2
  - http://images.platform9.com/ubuntu-14.04-cloudinit.qcow2
