---
- name: Check if pf9-ostackhost in installed (Ubuntu)
  shell: "`which dpkg-query` -s pf9-ostackhost > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: pkg_state_ostackhost_ubuntu
  when:
    - ansible_pkg_mgr == "apt"

- debug: msg="running multipath/tasks/ubuntu.yml"

- name: install multipath-tools
  apt:
    name: multipath-tools
    state: present
