---
- hosts: all
  become: true
  roles:
   - common
   - ntp
   - pf9-auth
   - pf9-hostagent

- hosts: hypervisors
  roles:
   - neutron-prerequisites

- hosts: image_storage
  roles:
    - glance-host
