---
- hosts: all
  become: true
  roles:
   - common
   - ntp
   - pf9-auth
   - pf9-hostagent

- hosts: hypervisors
  become: true
  roles:
   - neutron-prerequisites

# Note: the 'glance-host' role in incomplete; commenting out for now
#- hosts: image_storage
#  become: true
#  roles:
#    - glance-host
