---
- hosts:
    - hypervisors
    - containervisors
  become: true
  gather_facts: False
  pre_tasks:
    - name: install python2
      raw: if [ -e /etc/lsb-release -a ! -e /usr/bin/python ]; then (apt -y update && apt install -y python-minimal); fi
  roles:
    - common
    - ntp
    - pf9-auth
    - pf9-hostagent

- hosts: hypervisors
  become: true
  roles:
    - qemu-kvm-ev
    - neutron-prerequisites
    - { role: "map-role", rolename: "pf9-ostackhost-neutron", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-base", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-glance-role", when: autoreg == "on" and glance == "on" }
    - { role: "map-role", rolename: "pf9-celiometer-role", when: autoreg == "on" and ceilometer == "on" }
    - { role: "map-role", rolename: "pf9-neutron-ovs-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-l3-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-metadata-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-dhcp-agent", when: autoreg == "on" and dhcp == "on" }
    - { role: "glance-host", when: autoreg == "on" and glance == "on" }
    - secure-live-migration

- hosts: containervisors
  become: true
  roles:
    - { role: "map-role", rolename: "pf9-kube", when: autoreg == "on" }
