---
- hosts:
    - hypervisors-ubuntu
    - containervisors-ubuntu
  become: true
  gather_facts: False
  pre_tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts:
    - hypervisors
    - hypervisors-ubuntu
  become: true
  roles:
    - common
    - ntp
    - pf9-auth
    - pf9-hostagent
    - neutron-prerequisites
    - { role: "map-role", rolename: "pf9-ostackhost-neutron", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-base", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-glance-role", when: autoreg == "on" and glance == "on"}
    - { role: "map-role", rolename: "pf9-celiometer-role", when: autoreg == "on" and ceilometer == "on"}
    - { role: "map-role", rolename: "pf9-neutron-ovs-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-l3-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-metadata-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-dhcp-agent", when: autoreg == "on" and dhcp == "on"}

- hosts: containervisors
  become: true
  roles:
    - common
    - ntp
    - pf9-auth
    - pf9-hostagent
    - { role: "map-role", rolename: "pf9-kube" }

# Optional Role Assignments
- hosts: pf9-glance
  become: true
  roles:
    - glance-host
