---
# Common Roles
- hosts:
    - hypervisors
    - containervisors
  become: true
  gather_facts: False
  pre_tasks:
    - name: install python2
      raw: if [ -e /etc/lsb-release -a ! -e /usr/bin/python ]; then (apt -y update && apt install -y python-minimal); fi

# Openstack Hypervisor Nodes
- hosts: hypervisors
  become: true
  roles:
    - common
    - ntp
    - pf9-auth
    - pf9-hostagent
    - qemu-kvm-ev
    - neutron-prerequisites
    - { role: "map-role", rolename: "pf9-ostackhost-neutron", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-base", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-celiometer-role", when: autoreg == "on" and ceilometer == "on" }
    - { role: "map-role", rolename: "pf9-neutron-ovs-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-l3-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-metadata-agent", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-neutron-dhcp-agent", when: autoreg == "on" and dhcp == "on" }
    - { role: "secure-live-migration", when: autoreg == "on" }

# Openstack Image Nodes
- hosts: glance
  become: true
  roles:
    - { role: "glance-host", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-glance-role", when: autoreg == "on" }

# Openstack Block Storage Nodes
- hosts: cinder
  become: true
  roles:
    - lvm
    - { role: "map-role", rolename: "pf9-cindervolume-base", when: autoreg == "on" }
    - { role: "map-role", rolename: "pf9-cindervolume-lvm", when: autoreg == "on" }

# Kubernetes Master & Worker Nodes
- hosts: containervisors
  become: true
  roles:
    - common
    - ntp
    - pf9-auth
    - pf9-hostagent
    - { role: "map-role", rolename: "pf9-kube", when: autoreg == "on" }

