---
- hosts: hypervisors-ubuntu
  become: true
  gather_facts: False
  pre_tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: hypervisors
  become: true
  roles:
   - common
   - ntp
   - pf9-auth
   - pf9-hostagent
   - neutron-prerequisites
   #- secure-live-migration

- hosts: image_storage
  become: true
  roles:
    - glance-host
