---
- hosts: all
  roles:
   - common
   - ntp
   - pf9-auth
   - pf9-hostagent

- hosts: hypervisors
  roles:
   - neutron-prerequisites
   - secure-live-migration

- hosts: image_storage
  roles:
    - glance-host
