---
- name: Load kernel modules required for Neutron
  include: modules.yml

- name: Set sysctl variables for Neutron
  sysctl:
    state: present
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    ignoreerrors: true
  with_dict: "{{ neutron_sysctl }}"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Create required OVS bridges
  openvswitch_bridge:
    bridge: "{{ item }}"
    state: present
  with_items:
    - br-ext
    - br-vlan

- name: Set br-ext external bridge ID
  openvswitch_bridge:
    bridge: br-ext
    state: present
    external_ids:
      bridge-id: br-ext
