---
- name: Load kernel modules required for Neutron
  include: modules.yml

- name: Set sysctl variables for Neutron
  sysctl:
    state: present
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  with_dict: "{{ neutron_sysctl }}"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Create required OVS bridges
  openvswitch_bridge:
    bridge: "{{ item }}"
    state: present
  with_items:
    - br-pf9

- name: Set br-pf9 external bridge ID
  openvswitch_bridge:
    bridge: br-pf9
    state: present

- name: Set br-pf9 port as bond0
  openvswitch_port:
    bridge: br-pf9
    port: bond0
    state: present
