---
- name: Configure pf9 user on host
  user:
    name: pf9
    state: present
    shell: /bin/bash
    group: pf9group
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    update_password: on_create

- name: Create ~pf9/.ssh/config
  blockinfile:
    state: present
    block: |
      Host *
        User pf9
        StrictHostKeyChecking yes
        IdentityFile /opt/pf9/home/.ssh/id_rsa
        PasswordAuthentication no
    create: yes
    dest: /opt/pf9/home/.ssh/config

- name: Read pf9 user's public key
  slurp:
    src: /opt/pf9/home/.ssh/id_rsa.pub
  register: pf9_id_rsa

- name: Add authorized_key to other nodes
  authorized_key:
    user: pf9
    state: present
    key: "{{ pf9_id_rsa.content | b64decode }}"
  when: item != ansible_fqdn
  ignore_errors: true
  with_items: "{{ play_hosts }}"
  delegate_to: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"

- name: Add SSH keys for host(s)
  include: add-keys-for-host.yaml
  with_items: "{{ play_hosts }}"
  static: no
  loop_control:
    loop_var: host
