---

- debug: msg="running pre_flight_checks():"

###########################################################################################
## Verify DVR is on / validate step 1 in the UI is complete / test credentials
###########################################################################################

- name: read api token
  shell: "cat /tmp/keystone-token.txt"
  register: api_token

- name: validate DU global network settings have been configured
  uri:
    url: "https://{{ctrl_ip}}/resmgr/v1/services/neutron-server"
    method: GET
    body_format: json
    validate_certs: False
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{api_token.stdout.strip()}}"
  register: du_result
  delegate_to: localhost

- set_fact:
    du_neutron_type_drivers: "{{du_result.json.ml2.ml2.type_drivers}}"

- set_fact:
    net_list: "{{du_neutron_type_drivers.split(',')}}"
- set_fact:
    net_list_filtered: []

- name: build list of net types
  set_fact:
    net_list_filtered: '{{net_list_filtered + [item]}}'
  when: item != "flat"
  with_items: '{{net_list|list}}'

- set_fact:
    neutron_ovs_net_type: "{{ net_list_filtered | join(',') }}"

- set_fact:
    tunnel_ip: "{{ha_cluster_ip}}"
  when: tunnel_ip is undefined

- set_fact:
    neutron_tunnel_types: ""

- name: set vxlan_status
  set_fact:
    neutron_tunnel_types: "vxlan"
  when: item == "vxlan"
  with_items: '{{net_list|list}}'

- set_fact:
    neutron_ovs_enable_tunneling: "False"
- set_fact:
    neutron_ovs_enable_tunneling: "True"
  when: neutron_tunnel_types == "vxlan"

- fail: msg="ALERT - DVR is disabled. You must enable it or use the '-b' flag"
  when: skip_prereq == "0" and not du_result.json.neutron.DEFAULT.router_distributed

- debug: msg="neutron_ovs_net_type = {{neutron_ovs_net_type}}"
- debug: msg="neutron_tunnel_types = {{neutron_tunnel_types}}"

###########################################################################################
## validate free space in filesystem that the Cinder temp directory lives on
###########################################################################################

- block:
  - debug: msg="Validate minimum free space for cinder_image_conversion_cache (at least {{cinder_image_cache_min_free_space}} KBytes)"
  - name: get free space for cinder_image_conversion_cache
    shell: "df -k {{cinder_image_conversion_cache}} | tail -1 | awk '{print $2}'"
    register: cinder_cache_free_space
  - debug: var=cinder_cache_free_space
  
  - fail:
      msg="Insufficient free space in {{cinder_image_conversion_cache}} (mimimum required = {{cinder_image_cache_min_free_space}})"
    when: cinder_cache_free_space.stdout.strip() < cinder_image_cache_min_free_space
  when: inventory_hostname in groups['cinder']
