---
- block:
  - name: Enable and start Kernel SamePage Merging (RedHat)
    service:
      name: ksm
      state: started
      enabled: yes

  - name: Enable and start Kernel SamePage Merging Tuning
    service:
      name: ksmtuned
      state: started
      enabled: yes
  when: ansible_os_family == "RedHat"

- block:
  - name: Install Kernel SamePage Merging (Ubuntu)
    apt:
      name: ksmtuned
      state: latest

  - name: Enable and start Kernel SamePage Merging Tuning
    service:
      name: ksmtuned
      state: started
      enabled: yes
  when: ansible_os_family == "Ubuntu"
