---

- name: validate pf9/host_id.conf
  stat:
    path: /etc/pf9/host_id.conf
  register: stat_hostid

- fail: msg="failed to open /etc/pf9/host_id.conf"
  when: stat_hostid.stat.exists == false

- name: get host_id
  shell: cat /etc/pf9/host_id.conf | grep ^host_id | cut -d = -f2 | cut -d ' ' -f2
  register: host_id

- debug: msg="executing map-role.sh {{ctrl_ip}} {{rolename}} {{host_id.stdout.strip()}} {{du_username}} {{du_password}}"

- name: "Assigning Role - {{rolename}}"
  script: "map-role.sh {{ctrl_ip}} {{rolename}} {{host_id.stdout.strip()}} {{du_username}} {{du_password}}"
  delegate_to: localhost
  register: rolemap_log
  ignore_errors: true

- debug: var=rolemap_log.stdout_lines
