---
##########################################################################################################
## bond-config:
##
## Configure the physical and sub-interfaces behind the bond
##########################################################################################################

- include: redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
