---
##########################################################################################################
## bond-config:
##
## Configure the physical and sub-interfaces behind the bond
##########################################################################################################
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
