---
- debug: var=bond_members
- debug: var=bond_sub_interfaces

- block:
  - name: define physical interface
    template:
      src: ubuntu-ifcfg-interface.j2
      dest: "/etc/network/interfaces.d/ifcfg-{{bond_ifname}}.cfg"
      mode: 0644
    with_items: "{{bond_members}}"
  when: bond_members is defined

- block:
  - name: create the sub interfaces
    template:
      src: ubuntu-ifcfg-sub-interface.j2
      dest: "/etc/network/interfaces.d/ifcfg-{{bond_ifname}}-{{item['vlanid']}}.cfg"
      mode: 0644
    with_items: "{{bond_sub_interfaces|list}}"
  when: bond_sub_interfaces is defined

- name: restart network service
  service:
    name: networking
    state: restarted
  when: bond_members is defined or bond_sub_interfaces is defined
