---
################################################################################
# Read hostid and api token
################################################################################
- name: validate pf9/host_id.conf
  stat:
    path: /etc/pf9/host_id.conf
  register: stat_hostid

- fail: msg="failed to open /etc/pf9/host_id.conf"
  when: stat_hostid.stat.exists == false

- name: get host_id
  shell: cat /etc/pf9/host_id.conf | grep ^host_id | cut -d = -f2 | cut -d ' ' -f2
  register: host_id

- name: read api token
  shell: "cat /tmp/keystone-token.txt"
  register: api_token

################################################################################
# Attach to Cluster
################################################################################
- debug: msg="TOKEN = {{api_token.stdout.strip()}}"
- debug: msg="URI = https://{{ctrl_ip}}/qbert/v1/clusters/{{cluster_uuid}}/attach"
- debug: msg="BODY = {{host_id.stdout.strip()}}"

- name: "Attaching to Cluster : UUID = {{cluster_uuid}}"
  uri:
    url: "https://{{ctrl_ip}}/qbert/v1/clusters/{{cluster_uuid}}/attach"
    method: POST
    body: "['{{host_id.stdout.strip()}}']"
    body_format: json
    validate_certs: False
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{api_token.stdout.strip()}}"
  register: uri_result
  delegate_to: localhost
  ignore_errors: true

- debug: var=uri_result
