---
- name: ensure yum vars contentdir is present with proper value
  lineinfile:
    path: /etc/yum/vars/contentdir
    line: centos
    create: yes

- name: install the centos-release-qemu-ev repo
  yum:
    name: centos-release-qemu-ev
    state: latest
  when: ansible_os_family == "RedHat"

- name: install the latest version of qemu-kvm-ev
  yum:
    name: qemu-kvm-ev
    state: latest
  when: ansible_os_family == "RedHat"
